#! python3
# mcb.pyw - Saves and loads pieces of text to the clipboard.
# Usage: py.exe mcb.pyw save <keyword> - Saves clipboard to keyword.
#        py.exe mcb.pyw <keyword> - Loads keyword to clipboard.
#        py.exe mcb.pyw list - Loads all keywords to clipboard.
#        py.exe mcb.pyw delete <keyword> - removes a keyword
#        py.exe mvb.pwy delete - removes all of the saved keywords.

import shelve, pyperclip, sys

mcbShelf = shelve.open('mcbEXT')

if len(sys.argv) == 3:
    if sys.argv[1].lower() == 'save':
        mcbShelf[sys.argv[2]] = pyperclip.paste()       # saves clipboard content to keyword
    elif sys.argv[1] == 'delete':                       
        del mcbShelf[sys.argv[2]]                       # deletes given keyword
        
elif len(sys.argv) == 2:
    if sys.argv[1].lower() == 'list':
        pyperclip.copy(str(list(mcbShelf.keys())))      # copies list of keys to clipboard
    elif sys.argv[1].lower() == 'deleete':
        for i in list(mcbShelf.keys()):
            del i                                       # deletes all keywords
    elif sys.argv[1] in mcbShelf:
        pyperclip.copy(mcbShelf[sys.argv[1]])           # copies keyword's content to clipboard

mcbShelf.close()
