#! python3
# lookingBusy.py - nudges the mouse slightly every 3 seconds

import pyautogui, time
print('CTRL-C TO STOP')
try:
   while True:
      pyautogui.moveRel(30, 0.50)
      time.sleep(10)
      pyautogui.moveRel(-30, 0.50)
      
      
      
except KeyboardInterrupt:
   print('GET BACK TO WORK')
